workflows:
  web-workflow:
    name: Web Workflow
    environment:
      flutter: stable
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get

      - name: Flutter analyze
        script: |
          dart analyze

      - name: Flutter test
        script: |
          flutter test
          
      - name: Build for web
        script: | 
          flutter build web --release

      - name: Publish to Firebase Hosting
        script: | 
          firebase deploy --only hosting

    artifacts:
      - build/web.zip
      - flutter_drive.log

    publishing:
      email:
        recipients:
          - imdadadelabou0@gmail.com

environment:
  groups:
    - firebase_credentials:
        FIREBASE_SERVICE_ACCOUNT: $FIREBASE_SERVICE_ACCOUNT
