workflows:
  web-workflow:
    name: Web Workflow
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get

      - name: Flutter analyze
        script: |
          dart analyze

      - name: Flutter test
        script: |
          flutter test

      - name: Write Google credentials
        script: | 
          echo "$FIREBASE_SERVICE_ACCOUNT" > "$GOOGLE_APPLICATION_CREDENTIALS"


      - name: Build for web
        script: | 
          flutter build web --release
          cd build/web
          7z a -r ../web.zip ./*

      - name: Publish to Firebase Hosting
        script: | 
          firebase deploy

    artifacts:
      - build/web.zip
      - flutter_drive.log

    publishing:
      email:
        recipients:
          - imdadadelabou0@gmail.com
          - hamidtessilimi@gmail.com

    environment:
      flutter: stable
      groups:
        - firebase_credentials

          

