workflow:
  name: Build and deploy
  scripts:
    - name: Flutter analyze
      script: flutter analyze

    - name: Flutter test
      script: flutter test

    - name: Write Google credentials
      script: | 
        echo $FIREBASE_SERVICE_ACCOUNT > $GOOGLE_APPLICATION_CREDENTIALS

    - name: Build for web
      script: | 
        flutter build web

    - name: Publish to Firebase Hosting
      script: | 
        firebase deploy --only hosting

publishing:
  email:
    recipients:
      - imdadadelabou0@gmail.com


environment:
  groups:
    - firebase_credentials:
        FIREBASE_SERVICE_ACCOUNT: $FIREBASE_SERVICE_ACCOUNT
