name: google_clone
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts:
  google_sign_in:
  flutter_riverpod:
  json_annotation:
  dio:
  cached_network_image:
  gap:
  shared_preferences: ^2.2.2
  routemaster: ^1.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner:

flutter:
  uses-material-design: true
  assets:
    - assets/imgs/
