name: google_clone
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  cached_network_image:
  dio: ^5.4.1
  firebase_core:
  firebase_storage:
  flutter:
    sdk: flutter
  flutter_quill: ^9.3.1
  flutter_riverpod:
  gap:
  google_fonts:
  google_sign_in:
  image_picker: ^1.0.7
  json_annotation:
  routemaster: ^1.0.1
  shared_preferences: ^2.2.2
  socket_io_client: ^1.0.2
  


dev_dependencies:
  blackfoot_flutter_lint: ^2.0.0
  build_runner:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  json_serializable: ^6.7.1
  patrol: ^3.5.2
  test: ^1.24.9
  
 
  

patrol:
  app_name: docs.ai
  android:
    package_name: com.example.google_clone
  ios:
    bundle_id: com.example.googleClone
  
  
  

flutter:
  uses-material-design: true
  assets:
    - assets/imgs/
