name: google_clone
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  
  flutter_riverpod:
  gap:
  google_fonts:
  google_sign_in:
  json_annotation:
  routemaster: ^1.0.1
  shared_preferences: ^2.2.2
  cached_network_image:
  dio: ^5.4.1
  flutter_quill: ^9.3.1
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  blackfoot_flutter_lint: ^2.0.0
  build_runner:
  flutter_lints: ^3.0.0
  json_serializable: ^6.7.1
  
  
  

flutter:
  uses-material-design: true
  assets:
    - assets/imgs/
